spring:
  application:
    name: rest-springboot-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_springboot_java?useTimezone=true&serverTimezone=UTC
    username: developer
    password:
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: false
    open-in-view: false
